services:
  # State diffs indexer
  cryo-indexer-state:
    image: cryo-indexer:latest
    container_name: cryo-indexer-state
    volumes:
      - state_data:/app/data
      - state_logs:/app/logs
      - state_state:/app/state
      - ./migrations:/app/migrations
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE:-blockchain}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-9440} 
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE:-true}
      - CONFIRMATION_BLOCKS=${CONFIRMATION_BLOCKS:-20}
      - POLL_INTERVAL=${POLL_INTERVAL:-15}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - START_BLOCK=${STATE_START_BLOCK:-1}  # Default to block 1 for state diffs
      - END_BLOCK=${END_BLOCK:-0}
      - MAX_BLOCKS_PER_BATCH=${MAX_BLOCKS_PER_BATCH:-500}  # Smaller batch size for state diffs
      - OPERATION_MODE=scraper
      - INDEXER_MODE=state_diffs
      - INDEXER_STATE_FILE=indexer_state_state_diffs.json
      - NETWORK_NAME=${NETWORK_NAME:-gnosis}
    restart: unless-stopped

volumes:
  state_data:
  state_logs:
  state_state: