services:
  # Backfill service for targeted reindexing of specific ranges
  cryo-backfill:
    image: cryo-indexer:latest
    container_name: cryo-backfill-${BACKFILL_ID:-default}
    volumes:
      - backfill_data:/app/data
      - backfill_logs:/app/logs
      - backfill_state:/app/state
      - ./migrations:/app/migrations
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE:-blockchain}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-9440} 
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE:-true}
      - CONFIRMATION_BLOCKS=${CONFIRMATION_BLOCKS:-20}
      - POLL_INTERVAL=${POLL_INTERVAL:-15}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - START_BLOCK=${START_BLOCK:-0}
      - END_BLOCK=${END_BLOCK:-0}
      - MAX_BLOCKS_PER_BATCH=${MAX_BLOCKS_PER_BATCH:-1000}
      - OPERATION_MODE=scraper
      - INDEXER_MODE=${MODE:-${INDEXER_MODE:-custom}}
      - DATASETS=${DATASETS:-blocks,transactions,logs}
      - INDEXER_STATE_FILE=indexer_state_backfill_${BACKFILL_ID:-default}.json
      - NETWORK_NAME=${NETWORK_NAME:-gnosis}
    restart: "no"  # Run once and exit

volumes:
  backfill_data:
  backfill_logs:
  backfill_state: