services:
  # Traces indexer
  cryo-indexer-traces:
    image: cryo-indexer:latest
    container_name: cryo-indexer-traces
    volumes:
      - traces_data:/app/data
      - traces_logs:/app/logs
      - traces_state:/app/state
      - ./migrations:/app/migrations
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE:-blockchain}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-9440} 
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE:-true}
      - CONFIRMATION_BLOCKS=${CONFIRMATION_BLOCKS:-20}
      - POLL_INTERVAL=${POLL_INTERVAL:-15}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - START_BLOCK=${TRACES_START_BLOCK:-0}  # Default to block 0 for traces
      - END_BLOCK=${END_BLOCK:-0}
      - MAX_BLOCKS_PER_BATCH=${MAX_BLOCKS_PER_BATCH:-500}  # Smaller batch size for traces
      - OPERATION_MODE=scraper
      - INDEXER_MODE=traces
      - INDEXER_STATE_FILE=indexer_state_traces.json
      - NETWORK_NAME=${NETWORK_NAME:-gnosis}
    restart: unless-stopped

volumes:
  traces_data:
  traces_logs:
  traces_state: