services:
  # True multiprocess indexer service
  cryo-indexer-parallel:
    image: cryo-indexer:latest
    container_name: cryo-indexer-parallel
    volumes:
      - parallel_data:/app/data
      - parallel_logs:/app/logs
      - parallel_state:/app/state
      - ./migrations:/app/migrations
    environment:
      # Core settings
      - ETH_RPC_URL=${ETH_RPC_URL}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE:-blockchain}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-9440} 
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE:-true}
      - CONFIRMATION_BLOCKS=${CONFIRMATION_BLOCKS:-20}
      - POLL_INTERVAL=${POLL_INTERVAL:-15}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - START_BLOCK=${START_BLOCK:-0}
      - END_BLOCK=${END_BLOCK:-0}
      - MAX_BLOCKS_PER_BATCH=${MAX_BLOCKS_PER_BATCH:-1000}
      - OPERATION_MODE=parallel
      - INDEXER_MODE=${INDEXER_MODE:-default}
      - DATASETS=${DATASETS:-blocks,transactions,logs}
      - NETWORK_NAME=${NETWORK_NAME:-gnosis}
      
      # Multiprocess settings
      - PARALLEL_WORKERS=${PARALLEL_WORKERS:-4}
      - WORKER_BATCH_SIZE=${WORKER_BATCH_SIZE:-1000}
      - PYTHONUNBUFFERED=1
      - PYTHONFAULTHANDLER=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-4G}
          cpus: ${CPU_LIMIT:-4}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
          cpus: ${CPU_RESERVATION:-2}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  parallel_data:
  parallel_logs:
  parallel_state: