# --------------------------------------------------------------------------
# 0. Anchors / extension fields
# --------------------------------------------------------------------------
x-indexer-env: &indexer-env
  ETH_RPC_URL:  ${ETH_RPC_URL}
  NETWORK_NAME: ${NETWORK_NAME:-ethereum}

  CLICKHOUSE_HOST:     ${CLICKHOUSE_HOST}
  CLICKHOUSE_USER:     ${CLICKHOUSE_USER}
  CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
  CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE:-blockchain}
  CLICKHOUSE_PORT:     ${CLICKHOUSE_PORT:-8443}
  CLICKHOUSE_SECURE:   ${CLICKHOUSE_SECURE:-true}

  WORKERS:                 ${WORKERS:-1}
  BATCH_SIZE:              ${BATCH_SIZE:-100}
  MAX_RETRIES:             ${MAX_RETRIES:-3}
  REQUESTS_PER_SECOND:     ${REQUESTS_PER_SECOND:-30}
  MAX_CONCURRENT_REQUESTS: ${MAX_CONCURRENT_REQUESTS:-3}
  CRYO_TIMEOUT:            ${CRYO_TIMEOUT:-300}

  START_BLOCK:             ${START_BLOCK:-0}
  END_BLOCK:               ${END_BLOCK:-0}
  CONFIRMATION_BLOCKS:     ${CONFIRMATION_BLOCKS:-12}
  POLL_INTERVAL:           ${POLL_INTERVAL:-10}

  LOG_LEVEL: ${LOG_LEVEL:-INFO}

x-indexer-resources: &resources
  deploy:
    resources:
      limits:
        memory: 4G
        cpus: '2'
      reservations:
        memory: 2G
        cpus: '1'

# --------------------------------------------------------------------------
# 1. Volumes
# --------------------------------------------------------------------------
volumes:
  indexer_data_minimal:
  indexer_logs_minimal:
  indexer_data_extra:
  indexer_logs_extra:
  indexer_data_diffs:
  indexer_logs_diffs:
  indexer_data_full:
  indexer_logs_full:
  indexer_data_custom:
  indexer_logs_custom:

# --------------------------------------------------------------------------
# 2. Services
# --------------------------------------------------------------------------
services:
  cryo-indexer-minimal:
    image: cryo-indexer:latest
    container_name: cryo-indexer-minimal
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      <<: *indexer-env
      MODE: minimal
      OPERATION: ${OPERATION:-continuous}
    volumes:
      - indexer_data_minimal:/app/data
      - indexer_logs_minimal:/app/logs
      - ./migrations:/app/migrations
    <<: *resources

  cryo-indexer-extra:
    image: cryo-indexer:latest
    container_name: cryo-indexer-extra
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      <<: *indexer-env
      MODE: extra
      OPERATION: ${OPERATION:-continuous}
    volumes:
      - indexer_data_extra:/app/data
      - indexer_logs_extra:/app/logs
      - ./migrations:/app/migrations
    <<: *resources

  cryo-indexer-diffs:
    image: cryo-indexer:latest
    container_name: cryo-indexer-diffs
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      <<: *indexer-env
      MODE: diffs
      OPERATION: ${OPERATION:-continuous}
    volumes:
      - indexer_data_diffs:/app/data
      - indexer_logs_diffs:/app/logs
      - ./migrations:/app/migrations
    <<: *resources

  cryo-indexer-full:
    image: cryo-indexer:latest
    container_name: cryo-indexer-full
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      <<: *indexer-env
      MODE: full
      OPERATION: ${OPERATION:-continuous}
    volumes:
      - indexer_data_full:/app/data
      - indexer_logs_full:/app/logs
      - ./migrations:/app/migrations
    <<: *resources

  cryo-indexer-custom:
    image: cryo-indexer:latest
    container_name: cryo-indexer-custom
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      <<: *indexer-env
      MODE: custom
      DATASETS: ${DATASETS:-blocks,transactions,logs}
      OPERATION: ${OPERATION:-continuous}
    volumes:
      - indexer_data_custom:/app/data
      - indexer_logs_custom:/app/logs
      - ./migrations:/app/migrations
    <<: *resources

  # Migration job
  migrations:
    image: cryo-indexer:latest
    container_name: cryo-migrations-${TIMESTAMP:-default}
    profiles: ["migrations"]
    entrypoint: ["python", "-m", "src.db.migrations"]
    environment:
      CLICKHOUSE_HOST:     ${CLICKHOUSE_HOST}
      CLICKHOUSE_USER:     ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE:-blockchain}
      CLICKHOUSE_PORT:     ${CLICKHOUSE_PORT:-8443}
      CLICKHOUSE_SECURE:   ${CLICKHOUSE_SECURE:-true}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - ./migrations:/app/migrations

  # Historical indexing job
  historical-job:
    image: cryo-indexer:latest
    container_name: cryo-historical-${TIMESTAMP:-default}
    profiles: ["historical"]
    restart: "no"
    environment:
      <<: *indexer-env
      MODE: ${MODE:-minimal}
      OPERATION: historical
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./migrations:/app/migrations
    <<: *resources

  # Maintenance job
  maintain-job:
    image: cryo-indexer:latest
    container_name: cryo-maintain-${TIMESTAMP:-default}
    profiles: ["maintain"]
    restart: "no"
    environment:
      <<: *indexer-env
      MODE: ${MODE:-minimal}
      OPERATION: maintain
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./migrations:/app/migrations
    <<: *resources

  # Validation job
  validate-job:
    image: cryo-indexer:latest
    container_name: cryo-validate-${TIMESTAMP:-default}
    profiles: ["validate"]
    restart: "no"
    environment:
      <<: *indexer-env
      MODE: ${MODE:-minimal}
      OPERATION: validate
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./migrations:/app/migrations
    <<: *resources