name: Build & Release GC cryo-indexer

on:
    push:
      branches:
        - main

concurrency:
  group: cryo-indexer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Organization Name
        id: org_name
        run: |
          org_name=$(echo "${{ github.repository_owner }}")
          echo "Organization Name: $org_name"
          echo "org_name=$org_name" >> $GITHUB_OUTPUT

      - name: Extract commit
        id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ steps.org_name.outputs.org_name }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.org_name.outputs.org_name }}/gc-cryo-indexer:latest
            ghcr.io/${{ steps.org_name.outputs.org_name }}/gc-cryo-indexer:${{ steps.commit.outputs.short }}
          cache-from: type=registry,ref=ghcr.io/${{ steps.org_name.outputs.org_name }}/gc-cryo-indexer:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.org_name.outputs.org_name }}/gc-cryo-indexer:buildcache,mode=max